"""Root package for neuron-sink experiment infrastructure."""

from .attribution import (
    AttributionError,
    AttributionResult,
    attribution_rows,
    attribution_sha256,
    capture_c_proj_input,
    capture_mlp_projection_input,
    objective_depends_on_layer,
    rank_neurons,
    require_future_targets,
    score_example,
)
from .evaluation import (
    EvaluationError,
    ForwardSnapshot,
    SmokeCondition,
    aggregate_phenomenon_rows,
    evaluate_smoke_gate,
    forward_snapshot,
    paired_metrics,
    registered_smoke_conditions,
    validate_phenomenon_row,
)
from .model_adapters import (
    GPT2ModelAdapter,
    MLPModelAdapter,
    ModelStructureError,
    Qwen2ModelAdapter,
)
from .selection import (
    FrozenAttributionRanking,
    FrozenNeuronSets,
    SelectionCondition,
    SelectionError,
    build_selection_conditions,
    exact_k,
    generate_layer_matched_controls,
    load_frozen_attribution,
    load_frozen_neuron_sets,
    select_global_top_k,
)
from .suppression import NeuronSet, SuppressionContext, suppress_neurons

__all__ = [
    "AttributionError",
    "AttributionResult",
    "EvaluationError",
    "ForwardSnapshot",
    "FrozenAttributionRanking",
    "FrozenNeuronSets",
    "GPT2ModelAdapter",
    "MLPModelAdapter",
    "ModelStructureError",
    "NeuronSet",
    "Qwen2ModelAdapter",
    "SelectionCondition",
    "SelectionError",
    "SmokeCondition",
    "SuppressionContext",
    "attribution_rows",
    "attribution_sha256",
    "aggregate_phenomenon_rows",
    "capture_c_proj_input",
    "capture_mlp_projection_input",
    "build_selection_conditions",
    "exact_k",
    "evaluate_smoke_gate",
    "forward_snapshot",
    "generate_layer_matched_controls",
    "load_frozen_attribution",
    "load_frozen_neuron_sets",
    "objective_depends_on_layer",
    "paired_metrics",
    "rank_neurons",
    "registered_smoke_conditions",
    "require_future_targets",
    "score_example",
    "select_global_top_k",
    "suppress_neurons",
    "validate_phenomenon_row",
]
